//! Experimental, decision-local best response to an executable opponent policy.
//!
//! A complete legal observation is one decision bucket. All compatible worlds
//! choose the same action, maximizing their posterior-weighted terminal WP.
//! Opponent moves come ONLY from its observation-only policy, never from the
//! root-conditioned population (which contains the root player's actual hand).
//! The initial empirical posterior is conditioned on the real history once.
//! Subsequent hypothetical evidence is generated by the fixed opponent policy:
//! partitioning by its observed actions supplies the conditional reach weights.
//! No empirical likelihood is applied a second time to those future actions.
use super::{world_state, Model132Observation, Model132PeggingPolicy, PegCandidateForecast, World};
use crate::cards::score_count_ranks;
use crate::information_set::{PegSeat, RankPegAction, RankPegState};
use std::collections::{BTreeMap, HashMap};

type Outcomes = BTreeMap<(u8, u8), f64>;

#[derive(Clone)]
struct WeightedState {
    state: RankPegState,
    weight: f64,
}

#[derive(Default, Debug)]
pub(super) struct SearchStats {
    pub buckets: usize,
    pub candidate_branches: usize,
    pub transitions: usize,
    pub opponent_queries: usize,
    pub terminal_worlds: usize,
    pub largest_bucket: usize,
}

struct Bucket {
    observation: Model132Observation,
    worlds: Vec<WeightedState>,
}

struct Search<'a, P, F> {
    opponent: &'a P,
    utility: &'a mut F,
    origin: [i32; 2],
    utilities: BTreeMap<(u8, u8), f64>,
    stats: SearchStats,
    batch_size: usize,
    progress: Option<std::sync::Arc<crate::progress::DecisionProgress>>,
}

pub(super) fn forecast(
    observation: &Model132Observation,
    opponent: &impl Model132PeggingPolicy,
    worlds: Vec<World>,
    actions: &[RankPegAction],
    utility: &mut impl FnMut(u8, u8) -> f64,
) -> Result<(Vec<PegCandidateForecast>, SearchStats), String> {
    forecast_batched(observation, opponent, worlds, actions, utility, 32)
}

fn forecast_batched(
    observation: &Model132Observation,
    opponent: &impl Model132PeggingPolicy,
    mut worlds: Vec<World>,
    actions: &[RankPegAction],
    utility: &mut impl FnMut(u8, u8) -> f64,
    batch_size: usize,
) -> Result<(Vec<PegCandidateForecast>, SearchStats), String> {
    observation.validate()?;
    if worlds.is_empty() || actions.is_empty() || batch_size == 0 {
        return Err("20.5.pegging requires worlds, actions, and a positive batch size".into());
    }
    let legal = observation.legal_actions();
    if actions.iter().any(|action| !legal.contains(action)) {
        return Err("20.5.pegging requested an illegal root action".into());
    }
    // Canonical input order makes traversal independent of callers' world order.
    // Equal worlds can be split by a caller without creating distinct beliefs.
    worlds.sort_by(|a, b| a.remaining.cmp(&b.remaining)
        .then(a.discards.cmp(&b.discards)).then(a.weight.total_cmp(&b.weight)));
    let posterior_worlds = worlds.len();
    let mut merged: Vec<World> = Vec::with_capacity(worlds.len());
    for world in worlds {
        if !world.weight.is_finite() || world.weight < 0.0 {
            return Err("20.5.pegging received an invalid world weight".into());
        }
        if world.weight == 0.0 { continue; }
        if let Some(previous) = merged.last_mut().filter(|previous|
            previous.remaining == world.remaining && previous.discards == world.discards) {
            previous.weight += world.weight;
        } else {
            merged.push(world);
        }
    }
    let mass: f64 = merged.iter().map(|world| world.weight).sum();
    if !mass.is_finite() || mass <= 0.0 {
        return Err("20.5.pegging has no finite positive posterior mass".into());
    }
    let states = merged.iter().map(|world| Ok(WeightedState {
        state: world_state(observation, world)?, weight: world.weight / mass,
    })).collect::<Result<Vec<_>, String>>()?;
    let mut search = Search {
        opponent, utility, origin: [observation.my_score, observation.opponent_score],
        utilities: BTreeMap::new(), stats: SearchStats::default(), batch_size,
        progress: crate::progress::current(),
    };
    if let Some(progress) = &search.progress {
        progress.check_cancelled()?;
        progress.begin(actions.len());
    }
    let mut forecasts = Vec::with_capacity(actions.len());
    for (index, &action) in actions.iter().enumerate() {
        let outcomes = search.branch(&states, action)?;
        // Validate even a forced candidate's utility, and leave full histograms
        // available to review/calibration. No partial candidate or fallback.
        search.expected_wp(&outcomes)?;
        forecasts.push(PegCandidateForecast {
            action,
            outcomes: outcomes.into_iter().map(|((own, other), mass)| (own, other, mass)).collect(),
            posterior_worlds, evaluated_worlds: states.len(),
        });
        if let Some(progress) = &search.progress { progress.complete(index + 1); }
    }
    Ok((forecasts, search.stats))
}

impl<P: Model132PeggingPolicy, F: FnMut(u8, u8) -> f64> Search<'_, P, F> {
    fn check_cancelled(&self) -> Result<(), String> {
        if let Some(progress) = &self.progress { progress.check_cancelled()?; }
        Ok(())
    }

    fn apply(&mut self, world: &mut WeightedState, action: RankPegAction) -> Result<(), String> {
        world.state.apply_without_temporary_vectors(action)?;
        self.stats.transitions += 1;
        Ok(())
    }

    fn terminal(&mut self, world: &WeightedState, outcomes: &mut Outcomes) -> Result<(), String> {
        let score = (
            u8::try_from(world.state.scores[0] - self.origin[0])
                .map_err(|_| "20.5.pegging own score delta is out of range")?,
            u8::try_from(world.state.scores[1] - self.origin[1])
                .map_err(|_| "20.5.pegging opponent score delta is out of range")?,
        );
        *outcomes.entry(score).or_default() += world.weight;
        self.stats.terminal_worlds += 1;
        Ok(())
    }

    fn expected_wp(&mut self, outcomes: &Outcomes) -> Result<f64, String> {
        let mut total = 0.0;
        for (&score, &mass) in outcomes {
            let wp = *self.utilities.entry(score).or_insert_with(|| (self.utility)(score.0, score.1));
            if !wp.is_finite() || !(0.0..=1.0).contains(&wp) {
                return Err("20.5.pegging requires finite terminal WPs in [0, 1]".into());
            }
            total += mass * wp;
        }
        Ok(total)
    }

    fn branch(&mut self, worlds: &[WeightedState], action: RankPegAction) -> Result<Outcomes, String> {
        self.check_cancelled()?;
        self.stats.candidate_branches += 1;
        let mut active = worlds.to_vec();
        for world in &mut active { self.apply(world, action)?; }
        let mut outcomes = Outcomes::new();
        let mut indexes = HashMap::<Model132Observation, usize>::new();
        let mut buckets = Vec::<Bucket>::new();
        // Only the frontier is retained. There is no stored exhaustive path graph.
        // All worlds reaching the same A observation are collected BEFORE choosing.
        while !active.is_empty() {
            self.check_cancelled()?;
            let mut pending = Vec::new();
            let mut observations = Vec::new();
            for mut world in active {
                loop {
                    if world.state.complete || world.state.winner.is_some() {
                        self.terminal(&world, &mut outcomes)?;
                        break;
                    }
                    let legal = world.state.legal_actions();
                    if let [forced] = legal.as_slice() {
                        self.apply(&mut world, *forced)?;
                        continue;
                    }
                    if legal.is_empty() { return Err("20.5.pegging reached a dead nonterminal".into()); }
                    let observation = Model132Observation::from_state(&world.state, world.state.current)?;
                    if world.state.current == PegSeat::Zero {
                        let next = buckets.len();
                        let index = *indexes.entry(observation.clone()).or_insert(next);
                        if index == next { buckets.push(Bucket { observation, worlds: Vec::new() }); }
                        buckets[index].worlds.push(world);
                    } else {
                        observations.push(observation);
                        pending.push(world);
                    }
                    break;
                }
            }
            for (worlds, observations) in pending.chunks_mut(self.batch_size).zip(observations.chunks(self.batch_size)) {
                self.check_cancelled()?;
                let actions = self.opponent.choose_actions(observations)?;
                if actions.len() != worlds.len() {
                    return Err("20.5.pegging opponent returned an incorrect action count".into());
                }
                self.stats.opponent_queries += actions.len();
                for (world, action) in worlds.iter_mut().zip(actions) { self.apply(world, action)?; }
            }
            active = pending;
        }
        for bucket in buckets {
            let selected = self.choose_bucket(bucket)?;
            for (score, weight) in selected { *outcomes.entry(score).or_default() += weight; }
        }
        Ok(outcomes)
    }

    fn choose_bucket(&mut self, bucket: Bucket) -> Result<Outcomes, String> {
        self.stats.buckets += 1;
        self.stats.largest_bucket = self.stats.largest_bucket.max(bucket.worlds.len());
        let mut best: Option<((f64, u8, u8), Outcomes)> = None;
        for action in bucket.observation.legal_actions() {
            let outcomes = self.branch(&bucket.worlds, action)?;
            let wp = self.expected_wp(&outcomes)?;
            let RankPegAction::Play(rank) = action else {
                return Err("20.5.pegging encountered an unprocessed forced go".into());
            };
            let mut series = bucket.observation.current_series.clone();
            series.push(rank);
            let key = (wp, score_count_ranks(&series), rank);
            if best.as_ref().is_none_or(|(prior, _)| key > *prior) { best = Some((key, outcomes)); }
        }
        best.map(|(_, outcomes)| outcomes).ok_or_else(|| "20.5.pegging bucket has no action".into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::board::Role;
    use crate::information_set::PublicPegEvent;

    struct FirstLegal;
    impl Model132PeggingPolicy for FirstLegal {
        fn choose_action(&self, observation: &Model132Observation) -> Result<RankPegAction, String> {
            Ok(observation.legal_actions()[0])
        }
    }

    fn hand(ranks: &[usize]) -> [u8; 13] {
        let mut counts = [0; 13];
        for &rank in ranks { counts[rank] += 1; }
        counts
    }

    fn fixture() -> (Model132Observation, Vec<World>) {
        // Pone ten, dealer ten, pone ten, two goes: dealer now leads.
        // The opponent's next low card is common to both hidden hands.
        let observation = Model132Observation {
            role: Role::Dealer, my_score: 50, opponent_score: 51,
            own_remaining: hand(&[2, 4, 6]), own_played: hand(&[9]),
            opponent_played: hand(&[10, 11]), own_discards: hand(&[0, 1]),
            turn_rank: 8, current_series: vec![], count: 0,
            go_player: None, last_player: None,
            public_history: vec![PublicPegEvent::OpponentPlay(10), PublicPegEvent::SelfPlay(9),
                PublicPegEvent::OpponentPlay(11), PublicPegEvent::SelfGo,
                PublicPegEvent::OpponentGo, PublicPegEvent::Reset],
        };
        let worlds = vec![
            World { remaining: hand(&[3, 5]), discards: hand(&[0, 1]), weight: 0.75 },
            World { remaining: hand(&[3, 8]), discards: hand(&[0, 1]), weight: 0.25 },
        ];
        (observation, worlds)
    }

    fn wp(own: u8, other: u8) -> f64 { 0.5 + (f64::from(own) - f64::from(other)) / 100.0 }
    fn value(outcomes: &[(u8, u8, f64)]) -> f64 {
        outcomes.iter().map(|&(a, b, weight)| weight * wp(a, b)).sum()
    }

    // Independent reference: enumerate whole deterministic A strategies. When
    // an unassigned observation is encountered, try every action assignment and
    // replay ALL worlds from the root. This deliberately does not use buckets,
    // frontier partitioning, or the implementation's recursive value backup.
    fn exhaustive_strategy_value(
        initial: &[WeightedState], root: RankPegAction, origin: [i32; 2],
        policy: &mut HashMap<Model132Observation, RankPegAction>,
    ) -> f64 {
        let mut total = 0.0;
        for world in initial {
            let mut state = world.state.clone();
            state.apply(root).unwrap();
            while !state.complete && state.winner.is_none() {
                let legal = state.legal_actions();
                let action = if legal.len() == 1 || state.current == PegSeat::One {
                    legal[0]
                } else {
                    let observation = Model132Observation::from_state(&state, PegSeat::Zero).unwrap();
                    if let Some(action) = policy.get(&observation) { *action } else {
                        let mut best = f64::NEG_INFINITY;
                        for action in legal {
                            policy.insert(observation.clone(), action);
                            best = best.max(exhaustive_strategy_value(initial, root, origin, policy));
                            policy.remove(&observation);
                        }
                        return best;
                    }
                };
                state.apply(action).unwrap();
            }
            total += world.weight * wp((state.scores[0] - origin[0]) as u8,
                (state.scores[1] - origin[1]) as u8);
        }
        total
    }

    #[test]
    fn agrees_with_independent_exhaustive_legal_strategy_search() {
        let (mut observation, mut worlds) = fixture();
        for ranks in [[2, 4, 6], [3, 3, 8], [4, 7, 12], [1, 5, 9]] {
            observation.own_remaining = hand(&ranks);
            for probabilities in [[0.75, 0.25], [0.125, 0.875]] {
                for (world, probability) in worlds.iter_mut().zip(probabilities) { world.weight = probability; }
                let initial = worlds.iter().map(|world| WeightedState {
                    state: world_state(&observation, world).unwrap(), weight: world.weight,
                }).collect::<Vec<_>>();
                let (actual, stats) = forecast(&observation, &FirstLegal, worlds.clone(),
                    &observation.legal_actions(), &mut wp).unwrap();
                assert!(stats.transitions > 0);
                for candidate in actual {
                    let expected = exhaustive_strategy_value(&initial, candidate.action,
                        [observation.my_score, observation.opponent_score], &mut HashMap::new());
                    assert!((value(&candidate.outcomes) - expected).abs() < 1e-12,
                        "{ranks:?} {:?}: {} != {expected}", candidate.action, value(&candidate.outcomes));
                    assert!((candidate.outcomes.iter().map(|x| x.2).sum::<f64>() - 1.0).abs() < 1e-12);
                }
            }
        }
    }

    #[test]
    fn world_order_weight_splitting_and_batch_size_do_not_change_decisions_or_values() {
        let (observation, worlds) = fixture();
        let signature = |worlds, batch| {
            forecast_batched(&observation, &FirstLegal, worlds, &observation.legal_actions(), &mut wp, batch)
                .unwrap().0.into_iter().map(|f| (f.action, f.outcomes)).collect::<Vec<_>>()
        };
        let expected = signature(worlds.clone(), 32);
        let mut reversed = worlds.clone(); reversed.reverse();
        assert_eq!(signature(reversed, 1), expected);
        let split = worlds.iter().flat_map(|w| [World { weight: w.weight / 2.0, ..w.clone() },
            World { weight: w.weight / 2.0, ..w.clone() }]).collect();
        assert_eq!(signature(split, 3), expected);
    }

    #[test]
    fn hidden_world_best_moves_cannot_be_fused_into_an_unattainable_value() {
        let (mut observation, mut worlds) = fixture();
        let mut witnessed = false;
        'cases: for ranks in [[2, 4, 6], [3, 4, 8], [4, 7, 12], [1, 5, 9]] {
            observation.own_remaining = hand(&ranks);
            for hidden in 4..13 {
                worlds[1].remaining = hand(&[3, hidden]);
                let (joint, stats) = forecast(&observation, &FirstLegal, worlds.clone(),
                    &observation.legal_actions(), &mut wp).unwrap();
                let separate: Vec<_> = worlds.iter().map(|world| forecast(&observation, &FirstLegal,
                    vec![world.clone()], &observation.legal_actions(), &mut wp).unwrap().0).collect();
                for (index, candidate) in joint.iter().enumerate() {
                    let clairvoyant = worlds.iter().enumerate().map(|(w, world)|
                        world.weight * value(&separate[w][index].outcomes)).sum::<f64>();
                    assert!(value(&candidate.outcomes) <= clairvoyant + 1e-12);
                    if clairvoyant - value(&candidate.outcomes) > 1e-6 {
                        assert!(stats.largest_bucket > 1);
                        witnessed = true;
                        break 'cases;
                    }
                }
            }
        }
        assert!(witnessed, "fixture set must include an actual strategy-fusion counterexample");
    }

    #[test]
    fn complete_observation_excludes_opponent_private_cards_but_keeps_owned_information() {
        let (observation, worlds) = fixture();
        let first = world_state(&observation, &worlds[0]).unwrap();
        let mut changed = world_state(&observation, &worlds[1]).unwrap();
        changed.own_discards[1] = hand(&[5, 7]);
        assert_eq!(Model132Observation::from_state(&first, PegSeat::Zero).unwrap(),
            Model132Observation::from_state(&changed, PegSeat::Zero).unwrap());
        // At B's turn, changing A's hidden hand/discards cannot change B's query.
        let mut first = first; first.current = PegSeat::One;
        let mut changed = first.clone();
        changed.hands[0] = hand(&[5, 7, 8]); changed.own_discards[0] = hand(&[2, 3]);
        assert_eq!(Model132Observation::from_state(&first, PegSeat::One).unwrap(),
            Model132Observation::from_state(&changed, PegSeat::One).unwrap());
        changed.own_discards[1] = hand(&[5, 7]);
        assert_ne!(Model132Observation::from_state(&first, PegSeat::One).unwrap(),
            Model132Observation::from_state(&changed, PegSeat::One).unwrap());
    }

    #[test]
    fn scoreouts_stop_before_replies_and_cancellation_returns_no_partial_forecast() {
        let (mut observation, mut worlds) = fixture();
        observation.my_score = 119;
        observation.opponent_score = 120;
        observation.own_remaining[9] += 1;
        observation.own_played = [0; 13];
        observation.opponent_played = hand(&[11]);
        for world in &mut worlds { world.remaining[10] += 1; }
        observation.count = 10; observation.current_series = vec![11];
        observation.last_player = Some(crate::information_set::InfoActor::Opponent);
        observation.public_history = vec![PublicPegEvent::OpponentPlay(11)];
        let (actual, _) = forecast(&observation, &FirstLegal, worlds.clone(),
            &[RankPegAction::Play(4)], &mut |a, b| if a >= 2 { 1.0 } else if b >= 1 { 0.0 } else { 0.5 }).unwrap();
        assert_eq!(actual[0].outcomes, vec![(2, 0, 1.0)]);
        let progress = std::sync::Arc::new(crate::progress::DecisionProgress::default());
        progress.cancel();
        let error = crate::progress::with_progress(progress, ||
            forecast(&observation, &FirstLegal, worlds, &observation.legal_actions(), &mut wp).err().unwrap());
        assert_eq!(error, crate::progress::CANCELLED_ERROR);
    }

    #[test]
    fn invalid_probabilities_and_utilities_are_errors() {
        let (observation, worlds) = fixture();
        for bad in [f64::NAN, -1.0, f64::INFINITY] {
            let mut invalid = worlds.clone(); invalid[0].weight = bad;
            assert!(forecast(&observation, &FirstLegal, invalid, &observation.legal_actions(), &mut wp).is_err());
        }
        assert!(forecast(&observation, &FirstLegal, worlds, &observation.legal_actions(), &mut |_, _| f64::NAN).is_err());
    }
}
